### ISSUE TITLE
use absolute URIs instead of relative URIs

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/did-nostr#5]
suggestion made by @melvincarvalho 

<img width="420" alt="image" src="https://user-images.githubusercontent.com/4887440/226085996-a1222e30-315e-42d0-af5b-afb41d5e3b68.png">

**Comment by mistermoe** [comment]
[Relative DID URI section in did-core spec](https://www.w3.org/TR/did-core/#relative-did-urls)

<img width="805" alt="image" src="https://user-images.githubusercontent.com/4887440/226086145-5ae2bedb-1eef-45f0-a1c5-6f56234c68ff.png">

**Comment by csuwildcat** [comment]
I'm not sure why one would be unnecessarily verbose here and not just follow the spec for relative URIs. It's well-defined behavior, so I don't see a reason to bloat these documents.

**Comment by melvincarvalho** [comment]
@mistermoe, thank you for referencing this

Typically, I would suggest using relative #hash URIs as they can aid with portability and save a few characters. However, in the case of DID documents, there are already a lot of characters present.  The # identifier will be unique regardless, so portability never comes into play, and the processor will need to expand it, anyway. 

Unfortunately, this is one aspect of the DID Core specification that is somewhat unclear. When I raised a concern regarding the clarification of the document, base, type, controller, and subject, the response was an even messier diagram.

![image](https://user-images.githubusercontent.com/65864/226199344-f396ee40-c41b-4c89-b067-fce94952c13d.png)

The idea is to determine the base of the document out of band and add it as a prefix to the fragment. However, this approach ignores the fact that the base can be ambiguous or change on the web. It's a hack at best and an anti-pattern at worst.

The DID method used by Nostr can avoid this issue by being explicit. It's important for Nostr to have well-designed, clean identifiers that provide an advantage in scaling.

**Comment by metacatdud** [comment]
@melvincarvalho 

Man, this is disarmingly complex (not what is in this repo, but the w3 org specs in general). I seriously wonder (and question for that matter) if whoever came up with this complexity built these based on real-life, hands-on experiences. 

I am not trying to be dismissive in any way here, but I am just wondering if this entire thing is worth the trouble. Seem like a lot of head ake and whoever will want to build (even with this simplified version you are trying to design) for various languages will have to understand "the why".

IDK, maybe I am short-sighted and I can't see the big picture, but I refuse to believe there isn't a simple way.

Going over the diagram above is clear to me that whoever started this entire specification forgot where they left off and forgot where they are going.
